// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_nfLAB8ne6wY8IXQOD1gsNZSSvtQ2PU4',
    appId: '1:754916230014:web:d09466f54f1ad89111692f',
    messagingSenderId: '754916230014',
    projectId: 'eventgather-80639',
    authDomain: 'eventgather-80639.firebaseapp.com',
    storageBucket: 'eventgather-80639.appspot.com',
    measurementId: 'G-1WHVEMH88K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-G_NvGhmO6qhFR2NBdruPnUu_9eXAqw',
    appId: '1:754916230014:android:07b50b93be4a448511692f',
    messagingSenderId: '754916230014',
    projectId: 'eventgather-80639',
    storageBucket: 'eventgather-80639.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxPTCQTGscaQTPEZqaDIOMBNrvwESeRA',
    appId: '1:754916230014:ios:788533ef34fc9f6a11692f',
    messagingSenderId: '754916230014',
    projectId: 'eventgather-80639',
    storageBucket: 'eventgather-80639.appspot.com',
    iosBundleId: 'com.example.eventGather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxPTCQTGscaQTPEZqaDIOMBNrvwESeRA',
    appId: '1:754916230014:ios:254902cb0bc9d12011692f',
    messagingSenderId: '754916230014',
    projectId: 'eventgather-80639',
    storageBucket: 'eventgather-80639.appspot.com',
    iosBundleId: 'com.example.eventGather.RunnerTests',
  );
}
